# ===============================
# APPLICATION
# ===============================
server:
  port: 8080

# ===============================
# DATABASE
# ===============================
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/accounts_db
    username: accounts_user
    password: accounts123
    driver-class-name: org.postgresql.Driver

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
