server:
  port: 8888

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: accounts-route
              uri: lb://ACCOUNTS-TRUST
              predicates:
                - Path=/accounts/**
